/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: polyman (https://sketchfab.com/ely.haddad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/airpods-pro-with-magsafe-charging-case-ios15-52e5f28b37f94f05b6c0768773137689
Title: Airpods Pro With Magsafe Charging Case Ios15
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.gxCqFEWJNRsnkPj.geometry} material={materials.PaQiXaSGHRSDwze} />
        <mesh geometry={nodes.GlvnqzFONfCIEJq.geometry} material={materials.xwXDGCheXngfPki} />
        <mesh geometry={nodes.KPqSOEgJkfoJWgS.geometry} material={materials.eRyFUGhMcCIfWyS} />
        <mesh geometry={nodes.nHSAZuVqPlnoBxA.geometry} material={materials.BJknwphrEaDgKmq} />
        <mesh geometry={nodes.OQUywkShUFTTvZv.geometry} material={materials.ZHEOvCtfOUQXYsi} />
        <mesh geometry={nodes.vozJwbDYIPiPRkM.geometry} material={materials.IdRRtoGZFpOUFzk} />
        <mesh geometry={nodes.iEndOrEVfTGARlQ.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.coOlGWiFRsRNRvE.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.ORQCWMUHSwXewbr.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.WxnEChooRfePrAA.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.zQWewWOGCZBobQa.geometry} material={materials.PaQiXaSGHRSDwze} />
        <mesh geometry={nodes.NToXcEiFfCskVrC.geometry} material={materials.xwXDGCheXngfPki} />
        <mesh geometry={nodes.bPjepBAPhlWUSRe.geometry} material={materials.eRyFUGhMcCIfWyS} />
        <mesh geometry={nodes.WhJUWTqSHiZePoQ.geometry} material={materials.BJknwphrEaDgKmq} />
        <mesh geometry={nodes.eURoUelNkeWEPWy.geometry} material={materials.ZHEOvCtfOUQXYsi} />
        <mesh geometry={nodes.DXmztxyWNpsIlic.geometry} material={materials.IdRRtoGZFpOUFzk} />
        <mesh geometry={nodes.fRXkzMoefyvruCW.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.TmiWYYqpCykiIsE.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.tGbyvDYkGmwIHRM.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.tmlqocJjAqotiMz.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.ARiVeSiYKyNEkXZ.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.nGSbEKqYvhQjpmu.geometry} material={materials.voBqwXcOanrPWHW} />
        <mesh geometry={nodes.SJxQGgycOYnmQkj.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.GFhDdyvvBpxbwII.geometry} material={materials.ficvnSHYvUpBjZU} />
        <mesh geometry={nodes.UctfIqlHFesTeOo.geometry} material={materials.uWOKfMGMHyLyHBL} />
        <mesh geometry={nodes.WPUnAVXmUSEzEjD.geometry} material={materials.lMhVmbTLvOXZhTX} />
        <mesh geometry={nodes.WedkpIykuulKvMt.geometry} material={materials.ynStJiQdikNcHBw} />
        <mesh geometry={nodes.ovvBCJtLtXvnMKD.geometry} material={materials.ZHEOvCtfOUQXYsi} />
        <mesh geometry={nodes.rfmqyaJLfjAyTkY.geometry} material={materials.ZHEOvCtfOUQXYsi} />
        <mesh geometry={nodes.kvsOxYrjfUwuAsw.geometry} material={materials.lMhVmbTLvOXZhTX} />
        <mesh geometry={nodes.cnZEhMnQHWojrFG.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.eMQSQmnrMcrYOzA.geometry} material={materials.ficvnSHYvUpBjZU} />
        <mesh geometry={nodes.WPywCKzwFYPbAIO.geometry} material={materials.ZHEOvCtfOUQXYsi} />
        <mesh geometry={nodes.kcXIOLGHPvuqAhL.geometry} material={materials.CfiOHjkcSjNFvuF} />
        <mesh geometry={nodes.xuUooLuMANwvWJk.geometry} material={materials.lseAyrZVLwSNamy} />
        <mesh geometry={nodes.ukWJbdAAuCoFnDe.geometry} material={materials.voBqwXcOanrPWHW} />
        <mesh geometry={nodes.HprFYxCQYLORLvr.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.erqXhQpJfIKMidd.geometry} material={materials.BJknwphrEaDgKmq} />
        <mesh geometry={nodes.LImrPJrSiumUMPm.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.qBsRZnWVLmtLaiU.geometry} material={materials.ficvnSHYvUpBjZU} />
        <mesh geometry={nodes.aLSgkusWarWIoHN.geometry} material={materials.ficvnSHYvUpBjZU} />
        <mesh geometry={nodes.dhbkcOBiEDosgRO.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.MxHlnpCdYqRlihq.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.ltwtBjLQJodTgoH.geometry} material={materials.lMhVmbTLvOXZhTX} />
        <mesh geometry={nodes.HQvADjMMpJkPlAJ.geometry} material={materials.ynStJiQdikNcHBw} />
        <mesh geometry={nodes.BglGLwPPdrGXCru.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.JngTxmwkijQUWMZ.geometry} material={materials.UoApZRgmHmnlIkP} />
        <mesh geometry={nodes.XnmxbobttFBMayb.geometry} material={materials.UoApZRgmHmnlIkP} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
